vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../public/uploads/images'
            namer: vich_uploader.namer_uniqid
#        user_contracts:
#            uri_prefix: '%app.path.user_contracts%'
#            upload_destination: '%kernel.root_dir%/../public/uploads/files/user/contracts'

